#!/usr/bin/env php
<?php

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

require_once dirname(__DIR__) . "/Core/Helper/core.helper.php";
require_once basePath()."/vendor/autoload.php";
core()->run(false);
ConsoleRunner::run(new SingleManagerProvider(entityManager()));